### ISSUE TITLE
LWJGL 3 Support

### ISSUE THREAD

**Issue by Lyonlancer5** [Lenidevelaire/opsu-variant#10]
It's about time that experimental things were done, although this is slightly nuclear as it requires rewriting the codebase that depends on Slick2D. This will allow the addition of drag-and-drop support and other features that may have been added in LWJGL 3.

This may also improve the render engine, but yeah, definitely a nuclear option.

**Comment by Lyonlancer5** [comment]
-- disregard.

~~Rewrite everything as Project Aria so no licensing conflicts would be made.~~
~~Prefer also to do MIT/Apache for leniency stuff.~~

**Comment by Leidi-Kana** [comment]
Reopen because I found an existing local branch that already has LWJGL 3 support (although it's for version `0.15.0`) and will push to a new branch.

**Comment by Lyonlancer5** [comment]
Aight, but it's been a while since `0.15.0`.
Maybe just rewrite it instead of pushing an old unpublished branch, @Leidi-Kana?

**Comment by Lyonlancer5** [comment]
No published branch for `0.15.0/lwjgl-3-mod`, closing for the same reason as in the libGDX issue.
