### ISSUE TITLE
Libraries and licensing

### ISSUE THREAD

**Issue by Leidi-Kana** [Lenidevelaire/opsu-variant#13]
> GPL-3.0

Due to the license, some of the very important and useful stuff we use to work on other projects are technically not allowed to be used here. Sure, we can find another in maven, jcenter, sonatype, or write our own, but that would take just a bit more time and possibly some sub-1000 line changes to make it just work. (Depends on your luck and your chosen library 🤔)

You know, @Lyonlancer5, it may be better instead to rewrite stuff from scratch, considering how different our styles, libraries and licensing preferences are from theirs.

-------------------------

Apache-2.0 is "technically" compatible with the notions of the GPL-3.0, also considering you used it for your old Minecraft mod projects as well... So far, in talking to a few law practitioners and other software devs, it seems this is the best option compared to keep pushing updates to the origin.

Just work on Project Aria already, however, if you insist on working on this project, I can't stop you.
Everything I've worked on this project has been offline, so the moment I push my changes here, I'll stop working on this.

I'll be working on Project-Aria instead, using osu!lazer (MIT) as a base instead of the original opsu! (GPL) code.

**Comment by Lyonlancer5** [comment]
Check Discord DMs.
